%YAML 1.2
---

runner:
    build: ".."
    dockerfile: 'Dockerfile-integration'
    links:
        - "dnsaas:dnsaas"
        - "pdns:pdns"
        - "mysql:db"
dnsaas:
    build: ".."
    links: 
        - mysql:db
    environment:
        - DNSAAS_MYSQL_HOST=db
pdns:
    image: "zefciu/pdns"
    links:
        - mysql:db
mysql:
    image: "zefciu/mysql-with-data"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: dnsaas
        MYSQL_DATABASE: dnsaas
        MYSQL_PASSWORD: dnsaas
